### ISSUE TITLE
Getting assertion error after on uncompyle6

### ISSUE THREAD

**Issue by No-Cellist-7780** [extremecoders-re/pyinstxtractor#13]
getting the following error on using uncompyle on the extracted pyc file:
```
Traceback (most recent call last):
  File "D:\python\Scripts\uncompyle6-script.py", line 11, in <module>
    load_entry_point('uncompyle6==3.7.4', 'console_scripts', 'uncompyle6')()
  File "D:\python\lib\site-packages\uncompyle6\bin\uncompile.py", line 193, in main_bin
    result = main(src_base, out_base, pyc_paths, source_paths, outfile,
  File "D:\python\lib\site-packages\uncompyle6\main.py", line 316, in main
    deparsed = decompile_file(
  File "D:\python\lib\site-packages\uncompyle6\main.py", line 208, in decompile_file
    decompile(
  File "D:\python\lib\site-packages\uncompyle6\main.py", line 140, in decompile
    deparsed = deparse_fn(
  File "D:\python\lib\site-packages\uncompyle6\semantics\pysource.py", line 2572, in code_deparse
    tokens, customize = scanner.ingest(
  File "D:\python\lib\site-packages\uncompyle6\scanners\scanner38.py", line 45, in ingest
    tokens, customize = super(Scanner38, self).ingest(
  File "D:\python\lib\site-packages\uncompyle6\scanners\scanner37.py", line 42, in ingest
    tokens, customize = Scanner37Base.ingest(self, co, classname, code_objects, show_asm)
  File "D:\python\lib\site-packages\uncompyle6\scanners\scanner37base.py", line 209, in ingest
    bytecode = self.build_instructions(co)
  File "D:\python\lib\site-packages\uncompyle6\scanner.py", line 132, in build_instructions
    self.insts = self.remove_extended_args(list(bytecode))
  File "D:\python\lib\site-packages\xdis\bytecode.py", line 234, in get_instructions_bytes
    argrepr = opc.opcode_arg_fmt[opc.opname[op]](arg)
  File "D:\python\lib\site-packages\xdis\opcodes\opcode_37.py", line 121, in format_RAISE_VARARGS
    assert 0 <= argc <= 2
AssertionError
```

**Comment by extremecoders-re** [comment]
Without the pyc file or atleast a disassembly of the code it's hard to provide any helpful suggestions.

**Comment by No-Cellist-7780** [comment]
[The pyc file](https://mega.nz/file/VJhxnajL#J-twCjFT_AVAflw665pwd3GO5UjWF-Mwx18JH0Bps6A)
added to that when i try to uncompyle the PYZ extracted archieves it just stops uncompyle6 as a whole and doesnt output neither the error nor the code

**Comment by extremecoders-re** [comment]
This is neither a bug of pyinstxtractor or uncompyle6. If you try to disassemble the code using dis, it would fail the same way.

```
>>> import marshal
... import dis
... f=open('backup_decryptor.pyc','rb')
... f.seek(16)
... co=marshal.load(f)
>>> dis.dis(co)
  1           0 STORE_GLOBAL             0 (builtins)
        >>    2 STORE_GLOBAL             1 (bi)
              4 IMPORT_NAME              0 (builtins)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\administrator\miniconda3\envs\py38\lib\dis.py", line 79, in dis
    _disassemble_recursive(x, file=file, depth=depth)
  File "c:\users\administrator\miniconda3\envs\py38\lib\dis.py", line 373, in _disassemble_recursive
    disassemble(co, file=file)
  File "c:\users\administrator\miniconda3\envs\py38\lib\dis.py", line 369, in disassemble
    _disassemble_bytes(co.co_code, lasti, co.co_varnames, co.co_names,
  File "c:\users\administrator\miniconda3\envs\py38\lib\dis.py", line 401, in _disassemble_bytes
    for instr in _get_instructions_bytes(code, varnames, names,
  File "c:\users\administrator\miniconda3\envs\py38\lib\dis.py", line 345, in _get_instructions_bytes
    argval, argrepr = _get_name_info(arg, varnames)
  File "c:\users\administrator\miniconda3\envs\py38\lib\dis.py", line 304, in _get_name_info
    argval = name_list[name_index]
IndexError: tuple index out of range
```

The code is quite unusual as you don't see the `STORE_GLOBAL` instruction right at the start when the operand stack empty. 

Further, if you try to run the pyc on standard Python 3.8 in Linux it fails with a segfault.

```
$ python3 --version
Python 3.8.2
$ python3 backup_decryptor.pyc 
Segmentation fault (core dumped)
```

All of this strongly suggests that the Python interpreter which successfully "runs" this pyc uses different sets of instructions than the standard one. That is the opcodes have been changed. To decompile, you need to figure out the new opcodes, and remap them back to original after which uncompyle6 would work.

**Comment by No-Cellist-7780** [comment]
Thanks for that, got it now
