### ISSUE TITLE
Filed to unpack linux executable file

### ISSUE THREAD

**Issue by csorda** [extremecoders-re/pyinstxtractor#34]
[+] Processing .\LaunchProggram
[+] Pyinstaller version: 2.0
[+] Python version: 309
[+] Length of package: 10842163 bytes
Traceback (most recent call last):
  File "C:\Users\csord\Downloads\pyinstxtractor-master\pyinstxtractor.py", line 417, in <module>
    main()
  File "C:\Users\csord\Downloads\pyinstxtractor-master\pyinstxtractor.py", line 405, in main
    arch.parseTOC()
  File "C:\Users\csord\Downloads\pyinstxtractor-master\pyinstxtractor.py", line 235, in parseTOC
    struct.unpack( \
struct.error: unpack requires a buffer of 6925863 bytes

**Comment by MarkThe** [comment]
bro 
it does not decompile for me after i resetted my kali
:{

**Comment by extremecoders-re** [comment]
Looks to be using a modified version of PyInstaller.
Pyinstxtractor only works with the standard PyInsataller.
